vim9script

# Disable compatibility with vi.
set nocompatible

# Print the line number in front of each line.
set number

# Enable syntax highlighting.
syntax on

# Set vim's character encoding to utf-8.
set encoding=utf-8

# Enable true color (24-bit RGB color).
set termguicolors

# Disable saving/loading session information.
set viminfofile=NONE

# Always hide the statusline.
set laststatus=0

# Set the maximum width of a single line of text.
set textwidth=110

# Jump to the matched string when searching for a pattern.
set incsearch

# Highlight all the matches of the previous search pattern.
set hlsearch

# Update the characters to fill the statuslines, vertical separators and special lines in the window.
&fillchars = [
  # Remove the '|' characters used as vertical window separators. 
  'vert: ',
  # Remove the '~' characters in the empty lines below the end of a buffer.
  'eob: '
]->join(',')

# Set the <Leader> key.
g:mapleader = " "

# Movement key mappings.
nnoremap <c-r> $
nnoremap <c-q> ^
inoremap <c-j> <Down>
inoremap <c-k> <Up>
inoremap <c-l> <Right>
inoremap <c-h> <Left>
inoremap <c-r> <c-o>$
inoremap <c-q> <c-o>^

# Reload config key mapping. 
nnoremap <silent> <Leader>r :source $MYVIMRC<CR>:echo 'reloaded ' .. $MYVIMRC .. '.'<CR>

# Clear highlighted matches.
nnoremap <silent> <c-l> :nohlsearch<CR>
